### ISSUE TITLE
Crash with random things

### ISSUE THREAD

**Issue by medsal15** [maruohon/placementpreview#1]
The light redirector and your mod don't appear to go well together.
Note: The light redirector swaps 2 blocks' textures.

---

(Edited by masa:)
http://pastebin.com/akD4kupZ

Please use some pastebin service in the future instead of including the entire log directly in the comment, thanks.

**Comment by maruohon** [comment]
Are you able to reproduce this reliably? How exactly did this happen? I placed down a couple of Light Redirectors, and I'm previewing all around them without a crash...

**Comment by medsal15** [comment]
It happened when I placed a crafting table near one of them. I am unsure of the reason.

**Comment by maruohon** [comment]
Ok. Well I just released version 0.3.0, which should hopefully prevent this type of crashes in the future, although I still don't know how this could have happened anyway...
