### ISSUE TITLE
1.12.0-0.3.0 controls menu crash

### ISSUE THREAD

**Issue by HanabishiRecca** [maruohon/placementpreview#11]
1.12.0-0.3.0 crashes when trying to enter the "Controls" menu.
[crash-2017-06-14_13.51.11-client.txt](https://github.com/maruohon/placementpreview/files/1074040/crash-2017-06-14_13.51.11-client.txt)

**Comment by maruohon** [comment]
This is a generic issue in 1.12 atm, and it needs to be fixed in Forge. Any mod that adds its keybinds into a non-vanilla category will end up crashing the game atm, when opening the Controls menu.

**Comment by maruohon** [comment]
This has now been fixed in Forge 2324 or newer.
